# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=True, help_text=b'Make this the active announcement on the homepage.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, help_text=b'Full announcement text with more details.', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='short_description',
            field=models.CharField(help_text=b'Message that will appear in the homepage announcement section.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='exhibitionimage',
            name='caption',
            field=models.CharField(blank=True, default=b'', help_text=b'Optional: Caption for the photo.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='homepagebackground',
            name='name',
            field=models.CharField(help_text=b'Name to identify the background with.', max_length=256),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='featured',
            field=models.BooleanField(default=False, help_text=b'Make this the default entry.'),
        ),
        migrations.AlterField(
            model_name='word',
            name='sticky',
            field=models.BooleanField(default=False, help_text=b'Stick to the top of the list of entries.'),
        ),
    ]
